### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/efficiencyTracker#18]
Title is currently: "http://trshare.triumf.ca/~wjmills/GRIFFIN/efficiencyTracker/"

**Comment by BillMills** [comment]
I don't quite follow...? Sorry.

**Comment by SmithJK** [comment]
![screenshot from 2015-11-12 18 15 45](https://cloud.githubusercontent.com/assets/10604745/11137076/6df8f7cc-8969-11e5-8fbe-1c8ecb265e81.png)

**Comment by BillMills** [comment]
Ha! I spent like 5 solid minutes looking for a spelling error in the header.

Fixed.
